steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: "gcr.io/$PROJECT_ID/sonar-scanner:latest" 
    args: [
      "mvn clean install sonar:sonar", 
      "-Dsonar.projectKey=sonar-new", 
      "-Dsonar.sources=./src", 
      "-Dsonar.host.url=http://34.93.30.10:9000", 
      "-Dsonar.login=${_SONAR_TOKEN}",
      "-Dsonar.java.binaries=.",
      "-Dsonar.qualitygate.wait=true" ]
substitutions:
  _SONAR_TOKEN: "sqp_c367aec82f9d3c16b0589658ddbfe843842e92e8"
