apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springcicddemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohsinniveus/springcicddemo.git
    targetRevision: HEAD
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: default