apiVersion: v1
kind: Service
metadata:
  labels:
    app: canaryspringcicddemo
  name: canaryspringcicddemo
spec:
  ports:
  - port: 7070
    targetPort: 9090
  type: NodePort  
  selector:
    app:  canaryspringcicddemo
  