apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcicddemo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springcicddemo
  template:
    metadata:
      labels:
        app: springcicddemo
    spec:
      containers:
      - image: gcr.io/tech-rnd-project/springcicddemo:1.0.0
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        name: springcicddemo
        ports:
        - containerPort: 9090
          protocol: TCP 