apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: gcr.io/tech-rnd-project/springcicddemo
  newTag: 4.0.0
- name: gcr.io/tech-rnd-project/springcicddemo:4.0.0
  newTag: 4.0.0
