apiVersion: v1
kind: Service
metadata:
  labels:
    app: springcicddemo
  name:  springcicddemo
spec:
  ports:
  - port: 9090
    targetPort: 9090
  type: NodePort  
  selector:
    app: springcicddemo
  